# Generated by Django 5.2.5 on 2025-11-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0005_testretakerequest_is_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_paused",
            field=models.BooleanField(
                default=False, help_text="Test pauza qilinganmi?"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="paused_at",
            field=models.DateTimeField(
                blank=True, help_text="Test qachon pauza qilingan", null=True
            ),
        ),
    ]
