# Generated by Django 5.2.5 on 2025-11-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0006_test_is_paused_test_paused_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Savol uchun rasm (ixtiyoriy)",
                null=True,
                upload_to="question_images/",
            ),
        ),
    ]
